services: docker
dist: trusty
language: cpp
env:
  global:
  - DO_BUILD=yes
  - DO_TEST=yes
matrix:
  include:
  - compiler: gcc5
    env:
    - COMPILER=g++
    - IMG=gcc-5
    - CMAKE_EXTRA_FLAGS="-DENABLE_WARNINGS=On -DENABLE_CUDA=Off"
  - compiler: nvcc
    env:
    - COMPILER=g++
    - IMG=nvcc-9
    - CMAKE_EXTRA_FLAGS="-DENABLE_CUDA=On"
    - DO_TEST=no

script: 
- docker run --rm --user='root' -v ${TRAVIS_BUILD_DIR}:/home/axom axom/compilers:$IMG chown -R axom /home/axom
- docker run --rm  -v ${TRAVIS_BUILD_DIR}:/home/axom -e COMPILER -e DO_BUILD -e DO_TEST -e CMAKE_EXTRA_FLAGS axom/compilers:$IMG ./scripts/travis/build_and_test.sh

after_success:
- if [[ "${CMAKE_EXTRA_FLAGS}" == *"ENABLE_COVERAGE"* ]] ; then bash <(curl -s https://codecov.io/bash) -a "-f" >& /dev/null; fi
