trigger:
- develop

strategy:
  matrix: 
    linux: 
      imageName: 'ubuntu-16.04'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

variables:
  DO_BUILD: 'yes'
  DO_TEST: 'yes'
  COMPILER: 'g++'
  CMAKE_EXTRA_FLAGS: '-DENABLE_CUDA=Off'

steps:
- checkout: self
  clean: boolean
  submodules: recursive
- task: CMake@1
  inputs:
    workingDir: 'build'
    cmakeArgs: '$(CMAKE_EXTRA_FLAGS) ../'
  condition: eq( variables['Agent.OS'], 'Windows_NT')
- script:  |
   git submodule init && git submodule update --recursive
   docker run --rm --user='root' -v `pwd`:/home/axom axom/compilers:gcc-6 chown -R axom /home/axom
   docker run --rm  -v `pwd`:/home/axom -e COMPILER -e DO_BUILD -e DO_TEST -e CMAKE_EXTRA_FLAGS axom/compilers:gcc-6 ./scripts/travis/build_and_test.sh
  condition: eq( variables['Agent.OS'], 'Linux')

  displayName: 'build'
