on: push
name: Code Checks
jobs:
  staticAnalysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/static-analysis
  checkChangelog:
    name: Check CHANGELOG
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
    - run: |
        git fetch origin
        if sh -c "git diff origin/develop --exit-code $var"; then
            echo "$var wasn't changed, failing!"
            exit 255 
        else
            exit_code=$?
            echo "$var was changed, passing!"
            exit 0
        fi

